/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { MockERC20__factory } from "./MockERC20__factory";
export { PredictionMarket__factory } from "./PredictionMarket__factory";
export { PredictionMarketToken__factory } from "./PredictionMarketToken__factory";
export { YourContract__factory } from "./YourContract__factory";
