/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC165 } from "./IERC165";
export type { IReceiver } from "./IReceiver";
export type { ReceiverTemplate } from "./ReceiverTemplate";
