/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ReceiverTemplateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getExpectedAuthor"
      | "getExpectedWorkflowId"
      | "getExpectedWorkflowName"
      | "getForwarderAddress"
      | "onReport"
      | "owner"
      | "renounceOwnership"
      | "setExpectedAuthor"
      | "setExpectedWorkflowId"
      | "setExpectedWorkflowName"
      | "setForwarderAddress"
      | "supportsInterface"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExpectedAuthorUpdated"
      | "ExpectedWorkflowIdUpdated"
      | "ExpectedWorkflowNameUpdated"
      | "ForwarderAddressUpdated"
      | "OwnershipTransferred"
      | "SecurityWarning"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getExpectedAuthor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedWorkflowId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExpectedWorkflowName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getForwarderAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onReport",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedAuthor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedWorkflowId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExpectedWorkflowName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setForwarderAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getExpectedAuthor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedWorkflowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpectedWorkflowName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onReport", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedAuthor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedWorkflowId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExpectedWorkflowName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForwarderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ExpectedAuthorUpdatedEvent {
  export type InputTuple = [
    previousAuthor: AddressLike,
    newAuthor: AddressLike
  ];
  export type OutputTuple = [previousAuthor: string, newAuthor: string];
  export interface OutputObject {
    previousAuthor: string;
    newAuthor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpectedWorkflowIdUpdatedEvent {
  export type InputTuple = [previousId: BytesLike, newId: BytesLike];
  export type OutputTuple = [previousId: string, newId: string];
  export interface OutputObject {
    previousId: string;
    newId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpectedWorkflowNameUpdatedEvent {
  export type InputTuple = [previousName: BytesLike, newName: BytesLike];
  export type OutputTuple = [previousName: string, newName: string];
  export interface OutputObject {
    previousName: string;
    newName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForwarderAddressUpdatedEvent {
  export type InputTuple = [
    previousForwarder: AddressLike,
    newForwarder: AddressLike
  ];
  export type OutputTuple = [previousForwarder: string, newForwarder: string];
  export interface OutputObject {
    previousForwarder: string;
    newForwarder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecurityWarningEvent {
  export type InputTuple = [message: string];
  export type OutputTuple = [message: string];
  export interface OutputObject {
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReceiverTemplate extends BaseContract {
  connect(runner?: ContractRunner | null): ReceiverTemplate;
  waitForDeployment(): Promise<this>;

  interface: ReceiverTemplateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getExpectedAuthor: TypedContractMethod<[], [string], "view">;

  getExpectedWorkflowId: TypedContractMethod<[], [string], "view">;

  getExpectedWorkflowName: TypedContractMethod<[], [string], "view">;

  getForwarderAddress: TypedContractMethod<[], [string], "view">;

  onReport: TypedContractMethod<
    [metadata: BytesLike, report: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setExpectedAuthor: TypedContractMethod<
    [_author: AddressLike],
    [void],
    "nonpayable"
  >;

  setExpectedWorkflowId: TypedContractMethod<
    [_id: BytesLike],
    [void],
    "nonpayable"
  >;

  setExpectedWorkflowName: TypedContractMethod<
    [_name: string],
    [void],
    "nonpayable"
  >;

  setForwarderAddress: TypedContractMethod<
    [_forwarder: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getExpectedAuthor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getExpectedWorkflowId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getExpectedWorkflowName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getForwarderAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onReport"
  ): TypedContractMethod<
    [metadata: BytesLike, report: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedAuthor"
  ): TypedContractMethod<[_author: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedWorkflowId"
  ): TypedContractMethod<[_id: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExpectedWorkflowName"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setForwarderAddress"
  ): TypedContractMethod<[_forwarder: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ExpectedAuthorUpdated"
  ): TypedContractEvent<
    ExpectedAuthorUpdatedEvent.InputTuple,
    ExpectedAuthorUpdatedEvent.OutputTuple,
    ExpectedAuthorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpectedWorkflowIdUpdated"
  ): TypedContractEvent<
    ExpectedWorkflowIdUpdatedEvent.InputTuple,
    ExpectedWorkflowIdUpdatedEvent.OutputTuple,
    ExpectedWorkflowIdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpectedWorkflowNameUpdated"
  ): TypedContractEvent<
    ExpectedWorkflowNameUpdatedEvent.InputTuple,
    ExpectedWorkflowNameUpdatedEvent.OutputTuple,
    ExpectedWorkflowNameUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ForwarderAddressUpdated"
  ): TypedContractEvent<
    ForwarderAddressUpdatedEvent.InputTuple,
    ForwarderAddressUpdatedEvent.OutputTuple,
    ForwarderAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SecurityWarning"
  ): TypedContractEvent<
    SecurityWarningEvent.InputTuple,
    SecurityWarningEvent.OutputTuple,
    SecurityWarningEvent.OutputObject
  >;

  filters: {
    "ExpectedAuthorUpdated(address,address)": TypedContractEvent<
      ExpectedAuthorUpdatedEvent.InputTuple,
      ExpectedAuthorUpdatedEvent.OutputTuple,
      ExpectedAuthorUpdatedEvent.OutputObject
    >;
    ExpectedAuthorUpdated: TypedContractEvent<
      ExpectedAuthorUpdatedEvent.InputTuple,
      ExpectedAuthorUpdatedEvent.OutputTuple,
      ExpectedAuthorUpdatedEvent.OutputObject
    >;

    "ExpectedWorkflowIdUpdated(bytes32,bytes32)": TypedContractEvent<
      ExpectedWorkflowIdUpdatedEvent.InputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputObject
    >;
    ExpectedWorkflowIdUpdated: TypedContractEvent<
      ExpectedWorkflowIdUpdatedEvent.InputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputTuple,
      ExpectedWorkflowIdUpdatedEvent.OutputObject
    >;

    "ExpectedWorkflowNameUpdated(bytes10,bytes10)": TypedContractEvent<
      ExpectedWorkflowNameUpdatedEvent.InputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputObject
    >;
    ExpectedWorkflowNameUpdated: TypedContractEvent<
      ExpectedWorkflowNameUpdatedEvent.InputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputTuple,
      ExpectedWorkflowNameUpdatedEvent.OutputObject
    >;

    "ForwarderAddressUpdated(address,address)": TypedContractEvent<
      ForwarderAddressUpdatedEvent.InputTuple,
      ForwarderAddressUpdatedEvent.OutputTuple,
      ForwarderAddressUpdatedEvent.OutputObject
    >;
    ForwarderAddressUpdated: TypedContractEvent<
      ForwarderAddressUpdatedEvent.InputTuple,
      ForwarderAddressUpdatedEvent.OutputTuple,
      ForwarderAddressUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SecurityWarning(string)": TypedContractEvent<
      SecurityWarningEvent.InputTuple,
      SecurityWarningEvent.OutputTuple,
      SecurityWarningEvent.OutputObject
    >;
    SecurityWarning: TypedContractEvent<
      SecurityWarningEvent.InputTuple,
      SecurityWarningEvent.OutputTuple,
      SecurityWarningEvent.OutputObject
    >;
  };
}
