/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  11155111: {
    MockERC20: {
      address: "0xF991E0EB01B4B51Ab4bf8F1A3bF0968C90668473",
      abi: [
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "allowance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "balance",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "needed",
              type: "uint256",
            },
          ],
          name: "ERC20InsufficientBalance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "approver",
              type: "address",
            },
          ],
          name: "ERC20InvalidApprover",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "receiver",
              type: "address",
            },
          ],
          name: "ERC20InvalidReceiver",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "ERC20InvalidSpender",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        allowance: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        approve: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        balanceOf: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        decimals: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        name: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        symbol: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        totalSupply: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        transfer: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
        transferFrom: "@openzeppelin/contracts/token/ERC20/ERC20.sol",
      },
      deployedOnBlock: 10281432,
    },
    PredictionMarket: {
      address: "0x7CFA136d26AE91a663D1d655D3E373D6a049198C",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_liquidityProvider",
              type: "address",
            },
            {
              internalType: "address",
              name: "_oracle",
              type: "address",
            },
            {
              internalType: "string",
              name: "_question",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "_initialTokenValue",
              type: "uint256",
            },
            {
              internalType: "uint8",
              name: "_initialYesProbability",
              type: "uint8",
            },
            {
              internalType: "uint8",
              name: "_percentageToLock",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "_paymentToken",
              type: "address",
            },
            {
              internalType: "address",
              name: "_forwarderAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_initialLiquidityAmount",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "target",
              type: "address",
            },
          ],
          name: "AddressEmptyCode",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "AddressInsufficientBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "received",
              type: "address",
            },
            {
              internalType: "address",
              name: "expected",
              type: "address",
            },
          ],
          name: "InvalidAuthor",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidForwarderAddress",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "sender",
              type: "address",
            },
            {
              internalType: "address",
              name: "expected",
              type: "address",
            },
          ],
          name: "InvalidSender",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "received",
              type: "bytes32",
            },
            {
              internalType: "bytes32",
              name: "expected",
              type: "bytes32",
            },
          ],
          name: "InvalidWorkflowId",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "bytes10",
              name: "received",
              type: "bytes10",
            },
            {
              internalType: "bytes10",
              name: "expected",
              type: "bytes10",
            },
          ],
          name: "InvalidWorkflowName",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
          ],
          name: "OwnableInvalidOwner",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "OwnableUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__AmountMustBeGreaterThanZero",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_tradingAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_allowance",
              type: "uint256",
            },
          ],
          name: "PredictionMarket__InsufficientAllowance",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_tradingAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_userBalance",
              type: "uint256",
            },
          ],
          name: "PredictionMarket__InsufficientBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__InsufficientLiquidity",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "enum PredictionMarket.Outcome",
              name: "_outcome",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_amountToken",
              type: "uint256",
            },
          ],
          name: "PredictionMarket__InsufficientTokenReserve",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__InsufficientWinningTokens",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__InvalidPercentageToLock",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__InvalidProbability",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__MustProvideInitialLiquidity",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__OnlyOracleCanReport",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__OwnerCannotCall",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__PaymentTransferFailed",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__PredictionAlreadyReported",
          type: "error",
        },
        {
          inputs: [],
          name: "PredictionMarket__PredictionNotReported",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "SafeERC20FailedOperation",
          type: "error",
        },
        {
          inputs: [],
          name: "WorkflowNameRequiresAuthorValidation",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousAuthor",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newAuthor",
              type: "address",
            },
          ],
          name: "ExpectedAuthorUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "previousId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "newId",
              type: "bytes32",
            },
          ],
          name: "ExpectedWorkflowIdUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes10",
              name: "previousName",
              type: "bytes10",
            },
            {
              indexed: true,
              internalType: "bytes10",
              name: "newName",
              type: "bytes10",
            },
          ],
          name: "ExpectedWorkflowNameUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousForwarder",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newForwarder",
              type: "address",
            },
          ],
          name: "ForwarderAddressUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "provider",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "tokensAmount",
              type: "uint256",
            },
          ],
          name: "LiquidityAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "provider",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "tokensAmount",
              type: "uint256",
            },
          ],
          name: "LiquidityRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "oracle",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum PredictionMarket.Outcome",
              name: "winningOutcome",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "address",
              name: "winningToken",
              type: "address",
            },
          ],
          name: "MarketReported",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "resolver",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payoutAmount",
              type: "uint256",
            },
          ],
          name: "MarketResolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "message",
              type: "string",
            },
          ],
          name: "SecurityWarning",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "marketId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "question",
              type: "string",
            },
          ],
          name: "SettlementRequested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "buyer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum PredictionMarket.Outcome",
              name: "outcome",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "paymentAmount",
              type: "uint256",
            },
          ],
          name: "TokensPurchased",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "seller",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum PredictionMarket.Outcome",
              name: "outcome",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "paymentAmount",
              type: "uint256",
            },
          ],
          name: "TokensSold",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "redeemer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payoutAmount",
              type: "uint256",
            },
          ],
          name: "WinningTokensRedeemed",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "addLiquidity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PredictionMarket.Outcome",
              name: "_outcome",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_paymentAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_minTokensOut",
              type: "uint256",
            },
          ],
          name: "buyTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PredictionMarket.Outcome",
              name: "_outcome",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_paymentAmount",
              type: "uint256",
            },
          ],
          name: "calculateTokensForPayment",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PredictionMarket.Outcome",
              name: "_outcome",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_tradingAmount",
              type: "uint256",
            },
          ],
          name: "getBuyPrice",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getExpectedAuthor",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getExpectedWorkflowId",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getExpectedWorkflowName",
          outputs: [
            {
              internalType: "bytes10",
              name: "",
              type: "bytes10",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getForwarderAddress",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getPrediction",
          outputs: [
            {
              components: [
                {
                  internalType: "string",
                  name: "question",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "outcome1",
                  type: "string",
                },
                {
                  internalType: "string",
                  name: "outcome2",
                  type: "string",
                },
                {
                  internalType: "address",
                  name: "oracle",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "initialTokenValue",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "yesTokenReserve",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "noTokenReserve",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isReported",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "yesToken",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "noToken",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "winningToken",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "collateral",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "lpTradingRevenue",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "predictionMarketOwner",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "initialProbability",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "percentageLocked",
                  type: "uint256",
                },
              ],
              internalType: "struct PredictionMarket.PredictionDetails",
              name: "details",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PredictionMarket.Outcome",
              name: "_outcome",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_tradingAmount",
              type: "uint256",
            },
          ],
          name: "getSellPrice",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_initialTokenValue",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_initialYesProbability",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_noToken",
          outputs: [
            {
              internalType: "contract PredictionMarketToken",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_oracle",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_paymentToken",
          outputs: [
            {
              internalType: "contract IERC20",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_percentageLocked",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "i_yesToken",
          outputs: [
            {
              internalType: "contract PredictionMarketToken",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "initialize",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "metadata",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "report",
              type: "bytes",
            },
          ],
          name: "onReport",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "redeemWinningTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_amountToWithdraw",
              type: "uint256",
            },
          ],
          name: "removeLiquidity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PredictionMarket.Outcome",
              name: "_winningOutcome",
              type: "uint8",
            },
          ],
          name: "reportManually",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_marketId",
              type: "uint256",
            },
          ],
          name: "requestSettlement",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "resolveMarketAndWithdraw",
          outputs: [
            {
              internalType: "uint256",
              name: "payoutAmount",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "s_collateral",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "s_confidenceBps",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "s_evidenceURI",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "s_isReported",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "s_lpTradingRevenue",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "s_pendingInitialLiquidity",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "s_question",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "s_winningToken",
          outputs: [
            {
              internalType: "contract PredictionMarketToken",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum PredictionMarket.Outcome",
              name: "_outcome",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "_tradingAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_minRefund",
              type: "uint256",
            },
          ],
          name: "sellTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_author",
              type: "address",
            },
          ],
          name: "setExpectedAuthor",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_id",
              type: "bytes32",
            },
          ],
          name: "setExpectedWorkflowId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
          ],
          name: "setExpectedWorkflowName",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_forwarder",
              type: "address",
            },
          ],
          name: "setForwarderAddress",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {
        getExpectedAuthor: "contracts/interfaces/ReceiverTemplate.sol",
        getExpectedWorkflowId: "contracts/interfaces/ReceiverTemplate.sol",
        getExpectedWorkflowName: "contracts/interfaces/ReceiverTemplate.sol",
        getForwarderAddress: "contracts/interfaces/ReceiverTemplate.sol",
        onReport: "contracts/interfaces/ReceiverTemplate.sol",
        owner: "contracts/interfaces/ReceiverTemplate.sol",
        renounceOwnership: "contracts/interfaces/ReceiverTemplate.sol",
        setExpectedAuthor: "contracts/interfaces/ReceiverTemplate.sol",
        setExpectedWorkflowId: "contracts/interfaces/ReceiverTemplate.sol",
        setExpectedWorkflowName: "contracts/interfaces/ReceiverTemplate.sol",
        setForwarderAddress: "contracts/interfaces/ReceiverTemplate.sol",
        supportsInterface: "contracts/interfaces/ReceiverTemplate.sol",
        transferOwnership: "contracts/interfaces/ReceiverTemplate.sol",
      },
      deployedOnBlock: 10281433,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
