/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReceiver,
  IReceiverInterface,
} from "../../../contracts/interfaces/IReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "report",
        type: "bytes",
      },
    ],
    name: "onReport",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "interfaceId",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IReceiverInterface {
    return new Interface(_abi) as IReceiverInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IReceiver {
    return new Contract(address, _abi, runner) as unknown as IReceiver;
  }
}
