import * as fs from "fs";
import * as path from "path";

const deploymentsDir = path.join(__dirname, "../deployments/localhost");
const targetFile = path.join(__dirname, "../../nextjs/contracts/deployedContracts.ts");

// Read deployment files
const mockERC20 = JSON.parse(fs.readFileSync(path.join(deploymentsDir, "MockERC20.json"), "utf8"));
const predictionMarket = JSON.parse(fs.readFileSync(path.join(deploymentsDir, "PredictionMarket.json"), "utf8"));

// Create the deployedContracts object
const deployedContracts = {
    31337: {
        MockERC20: {
            address: mockERC20.address,
            abi: mockERC20.abi,
        },
        PredictionMarket: {
            address: predictionMarket.address,
            abi: predictionMarket.abi,
        },
    },
};

// Generate the TypeScript file
const fileContent = `/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = ${JSON.stringify(deployedContracts, null, 2)} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

fs.writeFileSync(targetFile, fileContent);
console.log("✅ Generated deployedContracts.ts");
console.log("   MockERC20:", mockERC20.address);
console.log("   PredictionMarket:", predictionMarket.address);
