import * as fs from "fs";
import * as path from "path";

const deploymentsDir = path.join(__dirname, "../deployments");
const targetFile = path.join(__dirname, "../../nextjs/contracts/deployedContracts.ts");

const chainIdMap: Record<string, number> = {
    "localhost": 31337,
    "hardhat": 31337,
    "avalancheFuji": 43113,
    "sepolia": 11155111,
};

function generate() {
    const deployedContracts: any = {};

    if (!fs.existsSync(deploymentsDir)) {
        console.log("No deployments directory found");
        return;
    }

    const networks = fs.readdirSync(deploymentsDir);

    for (const network of networks) {
        const networkPath = path.join(deploymentsDir, network);
        if (!fs.statSync(networkPath).isDirectory()) continue;

        const chainId = chainIdMap[network];
        if (!chainId) {
            console.log(`Skipping unknown network: ${network}`);
            continue;
        }

        deployedContracts[chainId] = {};

        const files = fs.readdirSync(networkPath);
        for (const file of files) {
            if (file.endsWith(".json")) {
                const contractName = file.replace(".json", "");
                const contractData = JSON.parse(fs.readFileSync(path.join(networkPath, file), "utf8"));
                deployedContracts[chainId][contractName] = {
                    address: contractData.address,
                    abi: contractData.abi,
                };
            }
        }
    }

    const fileContent = `/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = ${JSON.stringify(deployedContracts, null, 2)} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

    fs.writeFileSync(targetFile, fileContent);
    console.log("✅ Updated deployedContracts.ts for all networks");
}

generate();
